apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: 352588443787.dkr.ecr.us-east-1.amazonaws.com/wordsmith_db:1.3
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
          # valueFrom:
          #   secretKeyRef:
          #     name: db-secret
          #     key: username
        - name: POSTGRES_PASSWORD
          value: "password"
          # valueFrom:
          #   secretKeyRef:
          #     name: db-secret
          #     key: password
        ports:
        - containerPort: 5432
      #   volumeMounts:
      #   - name: init-sql
      #     mountPath: /docker-entrypoint-initdb.d/
      # volumes:
      # - name: init-sql
      #   configMap:
      #     name: db-init-sql

