apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordsmith
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AtongTerry/argocd-capstone.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: wordsmith
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
