apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"api\",\"app.kubernetes.io/instance\":\"wordsmith\"},\"name\":\"api\",\"namespace\":\"wordsmith\"},\"spec\":{\"replicas\":2,\"selector\":{\"matchLabels\":{\"app\":\"api\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"api\"}}},\"spec\":{\"containers\":[{\"name\":\"api\",\"image\":\"352588443787.dkr.ecr.us-east-1.amazonaws.com/wordsmith_api:1.1\",\"env\":[{\"name\":\"DB_HOST\",\"value\":\"db\"},{\"name\":\"DB_PORT\",\"value\":\"5432\"},{\"name\":\"DB_NAME\",\"value\":\"your_database_name\"},{\"name\":\"DB_USERNAME\",\"valueFrom\":{\"secretKeyRef\":{\"name\":\"db-secret\",\"key\":\"username\"}}},{\"name\":\"DB_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"name\":\"db-secret\",\"key\":\"password\"}}}],\"ports\":[{\"containerPort\":5000}]}]}}}}\n"
  labels:
    app: api
    app.kubernetes.io/instance: wordsmith
  name: api
  namespace: wordsmith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 352588443787.dkr.ecr.us-east-1.amazonaws.com/wordsmith_api:1.1
        env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: your_database_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        ports:
        - containerPort: 5000

